### ISSUE TITLE
Homework tests

### ISSUE THREAD

**Issue by ckcollab** [codalab/chagrade#25]

**Comment by madclam** [comment]
I tested homework creation in chagrade.lri.fr
- Defining the time: problem with editing homework time
- Last modified does not change
- Project URL is a short field

**Comment by madclam** [comment]
What happens if they change the Github submission URL after they submit the homework?

**Comment by Didayolo** [comment]
When as a student I submit homework with a "long" answer to a question (~3 sentences) I got a misleading error (like "all the fields needs to be filled"). 
I don't know if it was due to some special characters or the length of the answer. 

We need to be able to enter long answer and to have more informative error messages.
